name: Build and test (Linux)

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'examples/**'
      - '**.rs'
      - '**.toml'
      - '**.lock'
      - '.github/workflows/linux.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'examples/**'
      - '**.rs'
      - '**.toml'
      - '**.lock'
      - '.github/workflows/linux.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: hecrj/setup-rust-action@v2
      with:
        rust-version: 1.86.0
    - uses: actions/checkout@v4
    - name: Install deps
      run: |
       sudo apt-get update
       sudo apt-get install libpthread-stubs0-dev libgl1-mesa-dev libx11-dev libx11-xcb-dev libxcb-image0-dev libxrandr-dev libxcb-randr0-dev libudev-dev libfreetype6-dev libglew-dev libjpeg8-dev libgpgme11-dev libsndfile1-dev libopenal-dev libjpeg62 libxcursor-dev cmake libclang-dev clang
    - name: Build
      run: |
       git submodule update --init
       cargo build --verbose
    - name: Run tests
      run: |
       cargo test --features ci-headless --verbose
       # Release can have different build configuration, so test it
       cargo test --release --features=ci-headless --verbose
       # Also test non-default feature combinations
       cargo test --no-default-features --features=ci-headless --verbose
       cargo test --no-default-features --features=ci-headless,audio --verbose
       cargo test --no-default-features --features=ci-headless,window --verbose
       cargo test --no-default-features --features=ci-headless,graphics --verbose
       # Test packaging (building from .crate archive, without SFML submodule)
       cargo package
